{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aguilar.serviceAccountName" . }}
  labels:
{{ include "aguilar.labels" . | nindent 4 }}
{{- end -}}
